### ISSUE TITLE
Structure of CDTS/WebTemplates projects going forward

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#101]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/2

Calvin Rodo created this issue

I'm creating this project to discuss how we are going to move forward with a potential single group for CDTS/WebTemplate Types
One of my plans is to split the WebForms and MVC into two seperate projects see:
https://gccode.ssc-spc.gc.ca/GOCWebTemplates/DotNetTemplates/issues/161
https://gccode.ssc-spc.gc.ca/GOCWebTemplates/DotNetTemplates/issues/151
Originally I was thinking of just splitting things up at a package level but it might make sense to have a project per implementation in sgdc-cdts.
So we would have several new projects:

* sgdc-cdts/DotNetWebForms
* sgdc-cdts/DotNetMVC5
* sgdc-cdts/JSF20
* sgdc-cdts/JSF2x
* sgdc-cdts/JSP
* sgdc-cdts/JSP12c

I've also been asked about a .Net Core implementation so also it would have

* sgdc-cdts/DotNetCore1.1 or 2.0

Each of these projects would have a wiki associated with it that describes how to implement it in that project.
the GoCWebTemplates project would contain the back end code that we use to implement our stuff so we would have something like or that code could be included in the sgdc-cdts project so we could link issues with the core objects that are reported in each individual implementations issue tracker.

* GoCWebTemplate/DotNetCoreObject
* GoCWebTemplate/JavaCoreObject

That might be too many projects what do you guys think?

**Comment by MaximMartel** [comment]
Pierre Lupien commented:

As discussed a bit yesterday, that seems like a lot of projects to me... I am concerned about having all those separate issue trackers, having to re-define stuff like milestones, or having to tag all the projects separately upon release. There is also the fact the projects are kind of co-dependant (at least in Java, although I'm minimizing that more and more) and so pulling of JavaCoreObject without pulling/updating the other projects (or vice-versa) could lead to problems.

All that being said, I see your point and I think I see the value you're trying to bring. So I'm not totally opposed to the idea and am willing to discuss/explore the possibility...

In that spirit, I would tweak the original proposal above with:

* I would personally want to put all projects under the same group (i.e. the Core projects with the rest). What that group is to me is not important, but having them together seems easier to deal with.
* I'm not sure I would breakdown per version though... for example, I would tend to create a "JSF" Gitlab project containing both "JSF20" and "JSF2x" Eclipse projects.

At the risk of circling back: For that last point, I admit that a typical client would only need one of JSF20 or JSF2x, but Git to me is not the release channel, it's for maintainers. A typical maintainer will want to update both. For that matter, a typical maintainer, when making changes to JSF, will most likely want/need to make changes to JSP as well. And... chances are these changes are needed because of changes to the Core project.

Anyway, like I said still opened to it, just... concerned.

**Comment by shawnthompson** [comment]
@nicolasraymond have a look at this, if you haven't seen it before.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.
