### ISSUE TITLE
Search icon in mobile view

### ISSUE THREAD

**Issue by nicolasraymond** [wet-boew/cdts-sgdc#105]
If search is set to false, the search icon should not be there in mobile view.

**Comment by nicolasraymond** [comment]
In our application we don’t have a search bar, but when you switch to mobile view we get the search button (highlighted in the image below). Can this be disabled through the template?


 

Gaétan Tauvette

Programmer Analyst, Service Management
Transport Canada / Government of Canada
mailto:gaetan.tauvette@tc.gc.ca/ Cel: 613-462-1099 / TTY: 1-888-675-6863

Programmeur analyste, Gestion des services
Transports Canada / Gouvernement du Canada
mailto:gaetan.tauvette@tc.gc.ca/ Cell: 613-462-1099 / ATS : 1-888-675-6863

**Comment by nicolasraymond** [comment]
![image](https://user-images.githubusercontent.com/13963113/75156628-7ee7b980-56e0-11ea-9234-c361d489a519.png)

**Comment by ipaksc** [comment]
I tested CDTS versions v4_0_27 to v4_0_32. There was a minor issue with hiding the search button in mobile view.
 
The issue was fixed in v4_0_31. The issue the client has on his page is not related to the template. I recommended to upgrade the template to v4.0.32, since we are supporting only three last versions. I provided recommendations how to fix the issue, with search button in mobile view. I also recommend to review the HTML code, there are some semantic issues.
