### ISSUE TITLE
Change link https://www1.canada.ca/en/government/about.html

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#130]
In Canada.ca, the footer link “About Canada.ca” has been updated to https://www.canada.ca/en/government/about.html

This has been fixed in https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/samples_test/breadcrumbs-en.shtml. We will closed the issue it when release v4_0_32c will be released.

**Comment by laurencechavet** [comment]
Hi
I checked https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/samples_test/breadcrumbs-en.shtml. It seems the link "About Canada.ca" goes to https://www.canada.ca/en/newsite.html which is not the same URL than in canada.ca (https://www.canada.ca/en/government/about.html), even if it goes to the same page.
Thanks

**Comment by StdGit** [comment]
@laurencechavet Could we close this issue?
About Canada.ca from https://www.canada.ca/en.html goes to
https://www.canada.ca/en/government/about.html

**Comment by laurencechavet** [comment]
Hi
I was waiting for the release of 4.0.39 to answer. This is still not fixed

From https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html#Static_pages_.28version_.2F_run.29, we can get the static pages for the 4.0.39 and the link in the footer is still pointing to https://www.canada.ca/en/newsite.html instead of https://www.canada.ca/en/government/about.html. The static files in the CDTS package must be modified to match the WET.

![image](https://user-images.githubusercontent.com/65306416/104495064-45909480-55a5-11eb-834f-8f3e974c3d85.png)

Thanks

**Comment by ahmad-shahid** [comment]
Hi @laurencechavet, I just saw this issue. I went ahead and updated the link for About Canada.ca. 
The change is live now so you can re-download the zip file. Let me know if there are any issues.

**Comment by laurencechavet** [comment]
All good now
Thanks a lot
You can close the case
