### ISSUE TITLE
X-Frame-Options“ directive set to SAMEORIGIN

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#156]
These errors do not occur on the production server, but we will have them on all other servers like ssl-templates.services.gc.ca
The reason is because we are loading a file from WET that resides on the production server.

09:29:24.298 The loading of “https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/js/i18n/en.min.js” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.
en.min.js
09:29:24.305 The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

**Comment by StdGit** [comment]
@duboisp Are you aware of this issue?
I think it is similar to: https://github.com/wet-boew/wet-boew/issues/6653

From what I see our SSL servers is configure with 
X-Frame-Options | SAMEORIGIN

I will ask to our server teams to confirm that.

**Comment by duboisp** [comment]
Yes I am aware that we configured the X-Frame-Options http header to same origin on canada.ca. I think also I sent to CDTS team a notification about that too.

However, the CORS is configured to allow the file to be pulled with an AJAX call. 

What is your use case to load JS or any file through an iframe?

**Comment by StdGit** [comment]
@shawnthompson Do we have one?

**Comment by duboisp** [comment]
After looking at it, i think the issue is coming from Modernz and yepnope in wet-boew core which try to load the script asset via a frame. However the script are still loaded and operational. I didn't saw any explicit call that could probably load any script into a frame except 
Currently I suspect that probably the browser sandbox the execution of wet-boew.js because it is added into the page by using the `document.write` instruction. We should test an alternative method, cleaner, to load the javascript wet-boew.js to see if that would fix the issue and prevent the error log.

**Comment by StdGit** [comment]
thx Pierre Another place where we are using iframe is Google Tag Manager (GTM) . (Noscript)
I want to remove that too
https://github.com/wet-boew/cdts-sgdc/issues/123

`		
		<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5DBPCQJ"
		height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
		`

**Comment by StdGit** [comment]
These lines cause the error

`		<script>
			document.write(wet.builder.refFooter({
			}));
		</script>`

**Comment by ahmad-shahid** [comment]
We removed SSI statements. The files are loaded from the same server the page is loaded from.
