### ISSUE TITLE
Update Test Links

### ISSUE THREAD

**Issue by ahmad-shahid** [wet-boew/cdts-sgdc#364]
- [x] Change the order of tests
- [x] Investigate issuing warnings
- [x] Ignore the following URL: "https://recherche-search.gc.ca/rGs/s_r?#wb-land"

**Comment by plup2** [comment]
@ahmad-shahid   Turns out the warnings issued by the "workflow command" (https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions) do NOT show up in PRs.  

So I'll go with what we discussed: I'll add a check that will make it so if the environment variable `DISABLE_TESTLINKS_THROWONFAIL` is set, the scripts will show the error in the log but not throw the exception (ie not fail the pipeline).

For now, this variable will not be set in the pipeline.
