### ISSUE TITLE
RE: question re. Service Canada Issue with Chrome 80

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#48]
Moved from GCCode to Github : https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/150

@StdGit

[RE__question_re__Service_Canada_Issue_with_Chrome_80.zip](https://github.com/wet-boew/cdts-sgdc/files/4149678/RE__question_re__Service_Canada_Issue_with_Chrome_80.zip)

**Comment by MaximMartel** [comment]
@shawnthompson: We should be testing CDTS with Chrome on an external device like the Macbook testing has.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Nous devons tester pour confirmer.
Need testing to confirm 

Cookies changes

Chrome 85 is the first stable version of the web browser that will assign SameSite=Lax to cookies if no other SameSite attribute is specified by the site. Google's initial plan was to roll out the changes in Chrome 80 Stable but the company rolled back the SameSite cookie changes because of the global pandemic.

https://www.ghacks.net/2020/08/25/google-chrome-85-stable-release-information/

https://www.forbes.com/sites/kateoflahertyuk/2020/02/05/new-google-alert-as-experts-warn-chrome-80-cookie-changes-could-break-websites/?sh=c2b10d277140

Right now, the Chrome SameSite cookie default is: “None,” which allows third-party cookies to track users across sites. But from February, cookies will default into “SameSite=Lax,” which means cookies are only set when the domain in the URL of the browser matches the domain of the cookie — a first-party cookie.

https://digiday.com/media/what-is-chrome-samesite/

**Comment by ahmad-shahid** [comment]
CDTS does not directly use cookies. Closing this issue.
