### ISSUE TITLE
Add an example that demonstrate how to send the url of the page as a parameter when we click contact us

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#73]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/122

@StdGit created this issue

This issue is important, because if we miss something during the testing it will be really helpful to receive info from the users. We should be like Amazon. (Facilitate the process for what we want.)

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Le lien Contact pointe maintenant sur https://www.canada.ca/en/contact.html

Donc ce n'est plus valide,  car chaque département gère à sa façon cette fonctionnalité.

---

Contact link point now on https://www.canada.ca/en/contact.html

So it is not valid anymore since each department has their way to handle that functionality
