### ISSUE TITLE
One Property with multiple usages `footerSections`

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#95]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/13

@StdGit created the issue

The Property ``footerSections`` actually has 2 usages, a list of links or a list of footer sections.
This makes programming for this feature really difficult.

Could the usage for a list of links have the property name changed to ``footerLinks`` or something else that identifies the differences between the two.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

We did this so it would be backwards compatible. If we didn't keep the same name the old logic would have broken for anyone who used it.

Let's have a look and discuss this.

**Comment by MaximMartel** [comment]
@StdGit commented:

With JS it doesn't matter as much how a property is used because they aren't usually strongly typed, even if it is bad practice.  
When using other languages that are strongly typed this adds a lot of complexity to make it work. You can see all the changes I made here in the DotNetTempaltes https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/merge_requests/123/diffs?commit_id=1f864d8270df4cdf3547db1020abf635bc4ed723

I totally get that you want it to be backwards compatible, but the cost of this seems to high.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Kept for backwards compatibility. Closing issue.
